-- Generated by nwg-displays on 2026-05-27 at 16:25:19. Do not edit manually.

hl.monitor({
    output = "desc:Najing CEC Panda FPD Technology CO. ltd 0x0061",
    mode = "2560x1600@60.0",
    position = "0x0",
    scale = 2.0
})
