-- Generated by nwg-displays on 2026-05-26 at 22:42:16. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:Najing CEC Panda FPD Technology CO. ltd 0x0061",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Najing CEC Panda FPD Technology CO. ltd 0x0061"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:Najing CEC Panda FPD Technology CO. ltd 0x0061"
})
